/// <summary>Contains functions to reference commonly used types in the <c>System</c> namespace.</summary>
[<RequireQualifiedAccess; System.ObsoleteAttribute>]
module FSharpIL.Metadata.SystemType

open FSharpIL.Metadata.Unchecked

let inline private create builder assembly name =
    TypeRef(ResolutionScope.AssemblyRef assembly, Identifier.ofStr name, "System") |> referenceType builder

/// <summary>Adds a reference to the <see cref="T:System.Object"/> type.</summary>
/// <param name="builder"/>
/// <param name="mscorlib">
/// The assembly containing the <see cref="T:System.Object"/> type, which is <c>System.Private.CoreLib</c> for .NET Core.
/// </param>
let Object builder mscorlib = create builder mscorlib "Object"
/// <summary>
/// Adds a reference to the <see cref="T:System.Enum"/> type, which serves as the base class for enumeration types.
/// </summary>
let Enum builder mscorlib = create builder mscorlib "Enum"
/// <summary>Adds a reference to the <see cref="T:System.String"/> type.</summary>
let String builder mscorlib = create builder mscorlib "String"
/// <summary>Adds a reference to the <see cref="T:System.ValueType"/> type.</summary>
let ValueType builder mscorlib = create builder mscorlib "ValueType"

/// <summary>
/// Adds a reference to the <see cref="T:System.MulticastDelegate"/> type, which serves as the base class for delegate types
/// generated by the C# and F# compilers.
/// </summary>
let MulticastDelegate builder mscorlib = create builder mscorlib "MulticastDelegate"
/// <summary>Adds a reference to the <see cref="T:System.Delegate"/> type.</summary>
let Delegate builder mscorlib = create builder mscorlib "Delegate"
/// <summary>
/// Adds a reference to the <see cref="T:System.IAsyncResult"/> type, which is used for the <c>BeginInvoke</c> and
/// <c>EndInvoke</c> methods of delegate types.
/// </summary>
let IAsyncResult builder mscorlib = create builder mscorlib "IAsyncResult"
/// <summary>
/// Adds a reference to the <see cref="T:System.AsyncCallback"/> type, which is used for the return type of the
/// <c>BeginInvoke</c> method of delegate types.
/// </summary>
let AsyncCallback builder mscorlib = create builder mscorlib "AsyncCallback"

/// <summary>Adds a reference to the <see cref="T:System.Console"/> type.</summary>
/// <param name="builder"/>
/// <param name="consolelib">
/// The assembly containing the <see cref="T:System.Console"/> type, which is <c>System.Console</c> for .NET Core.
/// </param>
let Console builder consolelib = create builder consolelib "Console"
